server.port=8015
spring.application.name=email-service

spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USER:example@gmail.com}
spring.mail.password=${SMTP_PASS:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=${JWT_SECRET:YOUR_STRONG_RANDOM_JWT_SECRET_MIN_48_CHARS}
