server.port=8013
spring.application.name=order-service
spring.datasource.url=jdbc:postgresql://${DB_HOST:aws-0-ap-south-1.pooler.supabase.com}:${DB_PORT:6543}/${DB_NAME:postgres}?sslmode=require
spring.datasource.username=${DB_USER:postgres.vddtkiefzhcihdzxxlgp}
spring.datasource.password=${DB_PASS:Kiran@1435}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:YOUR_STRONG_RANDOM_JWT_SECRET_MIN_48_CHARS}

razorpay.key-id=${RAZORPAY_KEY_ID:fake_key_id}
razorpay.key-secret=${RAZORPAY_KEY_SECRET:fake_key_secret}
razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET:fake_webhook_secret}
